### ISSUE TITLE
npz data make

### ISSUE THREAD

**Issue by Sylvia-Vee** [cvg/SOLD2#11]
sorry to bother you, I have a question about the training data

how can I transfer customer data to below format data:

 """ Data entries in the npz file
        jmap: [J, H, W]    Junction heat map (H and W are 4x smaller)
        joff: [J, 2, H, W] Junction offset within each pixel (Not sure about offsets)
        lmap: [H, W]       Line heat map with anti-aliasing (H and W are 4x smaller)
        junc: [Na, 3]      Junction coordinates (coordinates from 0~128 => 4x smaller.)
        Lpos: [M, 2]       Positive lines represented with junction indices
        Lneg: [M, 2]       Negative lines represented with junction indices
        lpos: [Np, 2, 3]   Positive lines represented with junction coordinates
        lneg: [Nn, 2, 3]   Negative lines represented with junction coordinates
        """

**Comment by rpautrat** [comment]
Hi, these are the conventions used in the [Wireframe dataset](https://github.com/huangkuns/wireframe). The best would be to check their repo to understand how they generated it in the first place.

Note that you don't need this to train SOLD², this is only if you want to compare with the original lines of the Wireframe dataset. SOLD² is by definition self-supervised, so it doesn't require any label.

**Comment by Sylvia-Vee** [comment]
thanks very much
