### ISSUE TITLE
line segment detection evaluation and line segment description evaluation

### ISSUE THREAD

**Issue by luoyangg** [cvg/SOLD2#13]
Hi, thank you very much for your released code. I'm trying to reproduce your work. According to the steps of readme, I train SOLD2 on the wireframe dataset to get my own model. Then i intend to get the metrics of the model and compare them with those in the paper (Table 1 and Figure 4).However, I find that this part is missing in the repository (if I don't miss it). Can you share the code for line segment detection evaluation (repeatability, localization error) and line segment descriptor evaluation (accuracy, precision, recall).

**Comment by rpautrat** [comment]
Hi!

Indeed, the evaluation code is still missing for now. I can provide it with the implementation of the metrics and line distances. However this will require some code cleaning first. With CVPR this week and some summer travelling afterwards, I might only release it later in July probably.

**Comment by rpautrat** [comment]
An uncleaned version of the evaluation code was introduced here: https://github.com/cvg/SOLD2/issues/30#issuecomment-985026158, so I am closing this now.
