### ISSUE TITLE
Discrepancy in key name in loss.py and train_detector.yaml

### ISSUE THREAD

**Issue by triangleCZH** [cvg/SOLD2#14]
Hi, I notice that in https://github.com/cvg/SOLD2/blob/425468764b42595e7c1675d9015488a37426c163/model/loss.py#L61, you try to get attribute `junc_loss_func` from config, but it is named as `junction_loss_func` in both train_detector.yaml and train_full_pipeline.yaml.
It does not have further impact since the default option for `junc_loss_func` is `superpoint`, and it is the only option. But it might still be nicer if you check this small issue, thanks :)

**Comment by rpautrat** [comment]
Hi, good catch! Thanks for pointing this out, I just pushed the correction :)
