### ISSUE TITLE
Potential Problem for HA Label Export due to Ambiguity between mode and dataset_export_mode in wireframe_dataset.py

### ISSUE THREAD

**Issue by triangleCZH** [cvg/SOLD2#15]
Hi, it's me again:)
After I export pseudo label and get `wireframe_train.h5,` I found that my data are transformed, so are the labels, (in Fig.1). I will assume that we do not want this to happen when labeling the dataset, but only at training time. (If this is expected, I would be curious why). My observation is, the concepts of `dataset_export_mode` and `mode` might have been misused.
I followed the boolean value `dataset.mode` and find that:
1. `experiment.py`  has `mode='export'; export_dataset_mode=True`
2. in `export.py` we call `get_dataset(export_dataset_mode, dataset_cfg)` so that `dataset.mode = True`
3. in `wireframe_dataset.py`, most of the time, `self.mode` is either `train` or `test`, but in `__getitem__()`,  it seems like we want `mode` to be either `train` or `export`, which caused some problems. (see Fig. 2).
Under the current setting, `train_prerprocessing` will be called (assume descriptor is disabled), in which a lot of warping are applied.
4. Further into function `train_preprocessing`, you also have comment about the mode (see Fig. 3), which indicate that the either`mode` should be export here, or we are at the wrong function; but the export option is not passed into `wireframe_dataset.py`

Do you mind explaining the expected behavior and pointing out my misunderstanding? Thank you!
P.S.Sorry that I fail to make code blocks instead of screenshots :( 

Fig.1
<img width="708" alt="image" src="https://user-images.githubusercontent.com/20054340/123260670-d314d080-d4c3-11eb-8a63-86883bcbebcf.png">

FIg. 2
<img width="804" alt="image" src="https://user-images.githubusercontent.com/20054340/123262154-934ee880-d4c5-11eb-82ad-052e441047eb.png">

Fig. 3
<img width="596" alt="image" src="https://user-images.githubusercontent.com/20054340/123262418-dc06a180-d4c5-11eb-9834-b85d0c0ccb5c.png">

**Comment by triangleCZH** [comment]
Additionally, I also want to confirm if `junc_prob_mean` and `heatmap_prob_mean` are enough for exporting labels. Because I found a lot of things are written  in to `wireframe_train.h5`  in `export.py`(see Fig. 4), but they are not used in `convert_homography_results.py`.

Fig. 4
<img width="695" alt="image" src="https://user-images.githubusercontent.com/20054340/123266866-64874100-d4ca-11eb-962d-849ccec4646f.png">

**Comment by rpautrat** [comment]
Hi, mode='export' means that the code will be exporting instead of training. 'export_dataset_mode' on the contrary should be either 'train' or 'test', depending on which split of the dataset you want to generate the labels.

Did you modify the config file `wireframe_dataset.yaml`? By default, the fields 'gt_source_train' and 'gt_source_test' are commented, so that the default will be 'official', which is using the default wireframe dataset (not the exported labels). In this mode, there should not be any warp during the export. It should only happen when you are using some exported labels in 'gt_source_train' and 'gt_source_test'.

Regarding your second questions: yes, `junc_prob_mean` and `heatmap_prob_mean` are sufficient to export the pseudo ground truth. The other entries are more for debugging, visualization or if you wanted to use another aggregation than the simple mean.

**Comment by triangleCZH** [comment]
@rpautrat Thank you for your answer.
For the first question:  `self.mode = 'train'` and `self.gt_source = 'official'`, so it will go into `train_preprocessing` (see Fig. 2, correct me if I got it wrong, thanks). After it is in `train_preprocessing`, there does not seem to be a way to prevent the augmentations, unless disable them in yaml.
The point is, `test_preprocessing` seems to be the correct function to call, instead of `train_preprocessing`. But when determine it, it follows `if self.mode == 'train'`(see Fig. 2) and will always go into `train_preprocessing`. I feel like it expects the mode to be `train` or `export` here,  not `train` or `test`, which leads to oppositve meanings.
For the second question: thank you, yes, with the two it still works. hooray!

**Comment by rpautrat** [comment]
Indeed, you should disable both photometric and homographic augmentations in the config file before the export. I should have mentioned it in the Readme - I'll correct that now.

**Comment by triangleCZH** [comment]
@rpautrat Thank you for your clarification. Just one more tiny thing, maybe `random_scaling` choice also want to be disabled during the train label exporting:).  Thank you for your quick response, and I will close this issue now.

**Comment by rpautrat** [comment]
No, I don't think that `random_scaling` should have any impact if the gt_source is 'official'. Because the scale parameter is not used in `train_preprocessing` anyway.
