### ISSUE TITLE
Error when I run step3 on my own dataset

### ISSUE THREAD

**Issue by huidemie** [cvg/SOLD2#22]
Hello, thank you for sharing your code! I got this error when I run 'step3' on my own dataset. I notice the detection results in line_detection.py is all False for some image, and I think it may be the reason. But how can I solve this problem?
![1628080444(1)](https://user-images.githubusercontent.com/53325307/128181384-95c18fc8-c8ed-4108-a847-fec7980db7c7.png)

**Comment by rpautrat** [comment]
Hi, this is probably due because no junction was detected indeed. I have just pushed a simple fix that should solve your issue. Let me know if the problem persists.
