### ISSUE TITLE
KeyError: 'heatmap' at Step#4

### ISSUE THREAD

**Issue by miaoqiz** [cvg/SOLD2#23]
Hi there,

How are you?

Thanks so much for the framework!

I have been following along the steps to train.

When it comes to step#4:

**python experiment.py --mode train --dataset_config config/wireframe_dataset.yaml --model_config config/train_detector.yaml --exp_name sold2_wireframe**

At iter [3300 / 3334], there seems to be an error shown below:

------------------------------------------------------------------------------------------------------------------------------

Epoch [0 / 50] Iter [3300 / 3334] loss=-1.6196 (-0.5707), junc_loss=0.1721 (0.4134), heatmap_loss=0.1301 (0.1545), gpu_mem=13.0003GB
	 Junction     precision=0.1136 (0.0754) / recall=0.6889 (0.5507)
	 Junction nms precision=0.2158 (0.1273) / recall=0.1094 (0.0765)
	 Heatmap      precision=0.0775 (0.1067) / recall=0.0007 (0.0224)

================== Validation ==================
Traceback (most recent call last):
  File "experiment.py", line 227, in <module>
    export_dataset_mode=args.export_dataset_mode, device=device)
  File "experiment.py", line 110, in main
    train(args, dataset_cfg, model_cfg, output_path)
  File "experiment.py", line 82, in train
    train_net(args, dataset_cfg, model_cfg, output_path)
  File "SOLD2/train.py", line 190, in train_net
    epoch=epoch)
  File "SOLD2/train.py", line 437, in validate
    heatmap = data["heatmap"].cuda()
KeyError: 'heatmap'

------------------------------------------------------------------------------------------------------------------------------

Can you kindly advise how to fix it?

Thanks so much and have a good day!

**Comment by rpautrat** [comment]
Hi!

Since it is appearing in the very first epoch and it is a data issue (the ground truth heatmap is not found by the dataloader), I suspect that your training dataset is corrupted and some files or values are missing.

Could you maybe track the name of the file where the heatmap was not found, and check that this file exists in your dataset and if the ground truth file is well-formed?

**Comment by miaoqiz** [comment]
Hi,

Thanks for the quick reply! I appreciate it.

If the 3rd step is to generate the ground truth data, I did not see any issue. 

-----------------------------------------------------------------------
cd postprocess
python convert_homography_results.py <name of the previously exported file (e.g. "wireframe_train.h5")> <name of the new data with extracted line segments (e.g. "wireframe_train_gt.h5")> ../config/export_line_features.yaml
cd ..
-----------------------------------------------------------------------

I can re-generate the "wireframe_train_gt.h5" again. Then I will print out the name of file where the heatmap was not found.

Thanks so much and have a good weekend!

**Comment by rpautrat** [comment]
Yes, you can try to regenerate the ground truth, or alternatively launch a training and print the name of each file that is being loaded, so that you can see the name of the one where it crashes.

**Comment by miaoqiz** [comment]
@rpautrat Thanks so much for the advise! I regenerated the training and test pseudo ground truth at step#2, all is good now.

I have two more questions:

1. How to export pseudo ground truth from  custom wire-frame data. Should there be a process to convert RGB images to wire-frame dataset with a pre-trained model? For example, using the "[wireframe](https://github.com/huangkuns/wireframe)" framework?
2. How to generate junction points only? is there an inference function for that?

Thanks so much and have a good day!

**Comment by rpautrat** [comment]
Hi,

1. You can follow the instructions of this issue: https://github.com/cvg/SOLD2/issues/19. Basically, you can copy the structure of the `datasets/holicity_dataset.py` dataloader and adapt it to your own dataset, then run the steps 2 and 3 with it.
2. There is no ready-made inference to generate junctions only, but you can do a small modification to the [LineDetector](https://github.com/cvg/SOLD2/blob/main/model/line_detector.py) to have it output the variable 'junctions' in addition to the line segments.

**Comment by miaoqiz** [comment]
Thanks so much!
