### ISSUE TITLE
Key error in reading holicity dataset - visualize_exported_dataset notebook

### ISSUE THREAD

**Issue by miaoqiz** [cvg/SOLD2#25]
Hi, 

How are you?

Thanks so much for the help! I appreciate it.

When I play with the "visualize_exported_dataset" notebook and go to the holicity section, it seem to have the data loading issue shown below.

After printing out the keys of loaded "data1", it seems only have the following keys:

**dict_keys(['image', 'junctions', 'junction_map', 'line_map', 'heatmap', 'valid_mask', 'file_key'])**

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-18-c64bef877f7c> in <module>
      6 
      7 # Reference data
----> 8 ref_img = data1['ref_image'].numpy().squeeze()
      9 ref_junc = data1['ref_junctions'].numpy()
     10 ref_line_map = data1['ref_line_map'].numpy()

KeyError: 'ref_image'
---------------------------------------------------------------------------

Any advise is appreciated. 

Thanks so much and have a good weekend!

**Comment by rpautrat** [comment]
Hi,

The 'type' parameter of the dataset config file controls what will the dataloader return. When 'type=single', it returns only 'image', when 'type=paired_desc', it returns 'ref_image' and 'target_image'.

So in your case you need to use the 'paired_desc' option.

**Comment by miaoqiz** [comment]
Thanks for the quick advise! 

I was able to fix it by changing "type" to "paired_desc" and enabled "augmentation".

Have a good week!

**Comment by miaoqiz** [comment]
Just wondering what are the "object" exactly.

- ref_img = data1['ref_image'].numpy().squeeze()
- ref_junc = data1['ref_junctions'].numpy()
- ref_line_map = data1['ref_line_map'].numpy()
- ref_line_points = data1['ref_line_points'].numpy()

- "ref_img": are these the detected junction points?
- "ref_junc": are these the subset of junction points that can be used to form lines ( with lines drawn )
- "ref_line_map": not sure what it contain
- "ref_line_points": are these the ground-truth junction points and associated lines?

Thanks so much!

**Comment by rpautrat** [comment]
Hi,

- "ref_img": the original image.
- "ref_junc": the detected junction points in this image.
- "ref_line_map": a 2D matrix where cell (i, j) contains a 1 if there is a line between junctions i and j.
- "ref_line_points": sampling of points along every ground truth line, which is used in the descriptor training.

The corresponding "target_*" objects are the same, but in the warped view, yes.

**Comment by miaoqiz** [comment]
Thanks, @rpautrat!

Have you thought about point distribution issue in some of the images?

**Comment by rpautrat** [comment]
You mean if the points used in the descriptor training are not well spread across the image? This probably happens from time to time, but I don't think that it is a big issue. Or what did you mean exactly?
