### ISSUE TITLE
junction point descriptor

### ISSUE THREAD

**Issue by miaoqiz** [cvg/SOLD2#26]
Hi @rpautrat,

How are you?

Thanks so much for your help every time! I appreciate it.

Just wondering when we predict the junction points using "SOLD2", will it output "point coordinates", "descriptors", and etc. just like the one from "superpoint"?

Thanks so much and have a good week!

**Comment by rpautrat** [comment]
Hi,

If you use the 'self.line_detection' of the line matcher, you can access the following items 'descriptors', 'junctions', 'heatmap', and 'line_segments':
https://github.com/cvg/SOLD2/blob/492a71d6b9a9d8d14b6d6586627197d5f9a927f0/model/line_matcher.py#L55

**Comment by miaoqiz** [comment]
Hi @rpautrat,

Thanks so much! These descriptors are the junction points' descriptors, right?

I remember that in the CVPR presentation, there was a mention of "line descriptor". 

Thanks and have a good day!

Mio

**Comment by rpautrat** [comment]
No, they are the dense descriptor maps, covering the full image. To get the line descriptor, you need to sample 5 points between the endpoints of the line you are considering and extract the descriptor map at these points.

**Comment by miaoqiz** [comment]
Thanks, @rpautrat !

Are these descriptor maps at each point similar to the descriptor of each point in "superpoint"? 

Thanks!

**Comment by rpautrat** [comment]
Yes, that's the same idea, just with a different network backbone.

**Comment by miaoqiz** [comment]
Thanks, @rpautrat !

I referenced your sample [code](https://github.com/rpautrat/SuperPoint/blob/master/superpoint/match_features_demo.py#L19) on "superpoint" to do matching based on the detected junction points from "SOLD2".

Each pair of image only has one or two matching pair of points. Most the matching points on the edge of the images.

Is it something that you saw before? 

Thanks

**Comment by rpautrat** [comment]
I am not sure to understand what you did exactly. But the two repos are not meant to be used together, I don't think you can take the code from each and combine everything together so easily. The SOLD² descriptor is optimized for lines, while the one in SuperPoint is optimized for points. I never tried to use the SOLD² descriptor for point matching, but I would not be too surprised if it doesn't work properly when used outside of line matching.

**Comment by miaoqiz** [comment]
Got it! Thanks!

It is just that if you visually look at the junction points, some of them are actually good candidates for point matching.

**Comment by rpautrat** [comment]
The junctions, yes probably. But did you use the SOLD² descriptor, or the SuperPoint one? Because the SOLD² one is optimized to rather distinguish points within lines, which might not work properly for point matching.

**Comment by miaoqiz** [comment]
Got it. I used the descriptors from SOLD2. Is there a way to use junction points and the descriptors from "SuperPoint"?

Thanks!

**Comment by rpautrat** [comment]
You could use the [pre-trained SuperPoint model](https://github.com/magicleap/SuperPointPretrainedNetwork) and write your own code to use the SOLD² junctions with the SuperPoint descriptors.

**Comment by miaoqiz** [comment]
Thanks! Will do!

Also, for using trained model from step#4, do you have a sample configuration? 

I change the path of model in the python notebook of "match_lines" and changed the "mode" to "static". 

I also used the following function:

-----------------------------------------------------------------------------------------------------------

line_detector = LineDetector(
        config["model_cfg"], ckpt_path, device, config["line_detector_cfg"])

-----------------------------------------------------------------------------------------------------------

It generated the following error:

-----------------------------------------------------------------------------------------------------------

__init__(self, model_cfg, ckpt_path, device, line_detector_cfg, junc_detect_thresh)
     55         self.model = get_model(model_cfg, loss_weights)
     56         checkpoint = torch.load(ckpt_path, map_location=self.device)
---> 57         self.model.load_state_dict(checkpoint["model_state_dict"])
     58         self.model = self.model.to(self.device)
     59         self.model = self.model.eval()

~/.local/lib/python3.6/site-packages/torch/nn/modules/module.py in load_state_dict(self, state_dict, strict)
    837         if len(error_msgs) > 0:
    838             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
--> 839                                self.__class__.__name__, "\n\t".join(error_msgs)))
    840         return _IncompatibleKeys(missing_keys, unexpected_keys)
    841 

RuntimeError: Error(s) in loading state_dict for SOLD2Net:
	Missing key(s) in state_dict: "w_desc", "descriptor_decoder.convPa.weight", "descriptor_decoder.convPa.bias", "descriptor_decoder.convPb.weight", "descriptor_decoder.convPb.bias". 

-----------------------------------------------------------------------------------------------------------

**Comment by rpautrat** [comment]
Hi, you shouldn't change to static normally. If you run the detector only, you can use the detector-only config: [train_detector.yaml](https://github.com/cvg/SOLD2/blob/main/config/train_detector.yaml)
