### ISSUE TITLE
"ref_junction_map" not  in the field of  wireframe dataset

### ISSUE THREAD

**Issue by DongHappyyy** [cvg/SOLD2#29]
Thank you very much for your work, which has benefited me a lot. Now I have some problems in using it. Excuse me

![image](https://user-images.githubusercontent.com/61820204/142559775-a8621ea5-4d78-453d-9f1e-298c441b5d82.png)
 
![image](https://user-images.githubusercontent.com/61820204/142560747-2d5f59e0-0b9d-4650-aa74-b5f0a005ea85.png)

The fields read in the training file are in the wireframe_ There is no dataset.py file. So，What should I do?

**Comment by rpautrat** [comment]
Hi, I am not sure to understand your question, What do you mean by "there is no dataset.py file"? Why do you need such a file? I think I need a bit more context to understand your problem.

**Comment by rpautrat** [comment]
I am closing this now, assuming that you managed to solve your problem.
