### ISSUE TITLE
heatmap = data["heatmap"].cuda()

### ISSUE THREAD

**Issue by Wangman1** [cvg/SOLD2#3]
data has no keys named 'heatmap'
![image](https://user-images.githubusercontent.com/33320872/115706282-0b067700-a3a0-11eb-933c-d5f057810a22.png)

**Comment by rpautrat** [comment]
Hi,

Could give a bit more context?

From the list of keys, I guess that you are trying to load the official ground truth of the Wireframe dataset. There is simply no heatmap ground truth in the official ground truth.

To get a heatmap ground truth, you need to go through the steps detailed in the Readme to pretrain the network on the synthetic dataset (or directly reuse the provided pretrained model), then export the junction and line heatmap ground truth on the dataset of your choice, for example the Wireframe dataset (step 2).

**Comment by Wangman1** [comment]
thank u, i will try it~

**Comment by xuyongzhi** [comment]
Sorry to inquiry about this closed issue again. 
It seems only work when " gt_source_train: exported file".
When "gt_source_train : official ",  **wireframe_dataset.py / train_preprocessing()** outputs data {"heatmap_pos", "heatmap_neg", ...}:

>         
            return {
                "image": to_tensor(image),
                "junctions": to_tensor(junctions).to(torch.float32)[0, ...],
                "junction_map": to_tensor(junction_map).to(torch.int),
                "line_map_pos": to_tensor(
                    line_map_pos).to(torch.int32)[0, ...],
                "line_map_neg": to_tensor(
                    line_map_neg).to(torch.int32)[0, ...],
                "heatmap_pos": to_tensor(heatmap_pos).to(torch.int32),
                "heatmap_neg": to_tensor(heatmap_neg).to(torch.int32),
                "valid_mask": to_tensor(valid_mask).to(torch.int32)
            } 
            
However, data["heatmap"] is required.
Should with just copy an element of data["heatmap"] = data["heatmap_pos"] ?

**Comment by rpautrat** [comment]
Yes, sorry if I was not clear, but basically you shouldn't use the official ground truth. This method is not meant to be used like this, it is a self-supervised method and shouldn't rely on the official ground truth. If you want to retrain the model, you need to follow the steps explained in the Readme by creating your own exported ground truth and then you can use "gt_source_train: exported file".

"gt_source_train : official" is only here for backward compatibility with the actual Wireframe dataset, and to evaluate our the descriptor using the official lines. It is not meant to be used when training the method.

**Comment by xuyongzhi** [comment]
Got it. Thanks!
