### ISSUE TITLE
Could you provide the synthetic datasets?

### ISSUE THREAD

**Issue by EchoTHChen** [cvg/SOLD2#32]
Hi, I'm very curious about how I could train a new model with your synthetic dataset. Could you tell me the way to download and use the synthetic dataset.

**Comment by rpautrat** [comment]
Hi, If you run the command in Step 1 of the Readme, this will automatically create the synthetic dataset for you. It should take a few minutes, so it is as easy as downloading it.

To train a new model, I suggest that you look at the code and replicate what has been done for our own line detector. This is in particular the dataloader to process the synthetic images: https://github.com/cvg/SOLD2/blob/main/dataset/synthetic_dataset.py

**Comment by EchoTHChen** [comment]
Thank you very much for your quick reply!



---Original---
From: "Rémi ***@***.***&gt;
Date: Tue, Dec 7, 2021 19:01 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cvg/SOLD2] Could you provide the synthetic datasets? (Issue #32)




 
Hi, If you run the command in Step 1 of the Readme, this will automatically create the synthetic dataset for you. It should take a few minutes, so it is as easy as downloading it.
 
To train a new model, I suggest that you look at the code and replicate what has been done for our own line detector. This is in particular the dataloader to process the synthetic images: https://github.com/cvg/SOLD2/blob/main/dataset/synthetic_dataset.py
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
