### ISSUE TITLE
About lines matching

### ISSUE THREAD

**Issue by zhangjunyu2020** [cvg/SOLD2#33]
Hello!
Is the line featurematching code part open source now? Because I didn't find the relevant parts when I was learning the code. 
The code is so cool.

**Comment by zhangjunyu2020** [comment]
The problem may be that I'm new 0.0

**Comment by rpautrat** [comment]
Hi, the code for line matching has been released from the beginning. You can find it in [line_matcher.py](https://github.com/cvg/SOLD2/blob/main/model/line_matcher.py) and an example of its usage can be found in [match_lines.ipynb](https://github.com/cvg/SOLD2/blob/main/notebooks/match_lines.ipynb).

**Comment by zhangjunyu2020** [comment]
Hello
Thank you for your timely reply, I really didn't read carefully, I found it now, your SOLD2 is really excellent, I'll keep studying.
thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cvg/SOLD2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月12日(星期天) 下午4:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cvg/SOLD2] About lines matching (Issue #33)





 
Hi, the code for line matching has been released from the beginning. You can find it in line_matcher.py and an example of its usage can be found in match_lines.ipynb.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhangjunyu2020** [comment]
star!
