### ISSUE TITLE
what command can be used to output pictures.

### ISSUE THREAD

**Issue by jinyayayaya** [cvg/SOLD2#34]
Sorry, I am a rookie. I would like to ask what command can be used to output pictures. I am very interested in this.

**Comment by rpautrat** [comment]
The notebook [match_lines.ipynb](https://github.com/cvg/SOLD2/blob/main/notebooks/match_lines.ipynb) is drawing the predicted lines in an image. All you need to do to save the image in a file is to add at the end a plt.savefig(<your_filename>).

**Comment by jinyayayaya** [comment]
thanks a lot！！！
