### ISSUE TITLE
some errors when retrain on sold2_wireframe.tar

### ISSUE THREAD

**Issue by xy-git** [cvg/SOLD2#35]
Thank you for your work !
I run the step5 on sold2_wireframe.tar like:
python experiment.py --mode train --dataset_config config/wireframe_dataset.yaml --model_config config/train_full_pipeline.yaml --exp_name sold5 --pretrained --pretrained_path ./exp  --checkpoint_name sold2_wireframe.tar
Then i run match_lines.py in notebooks using the checkpopint that I run out, find the errors:
`Traceback (most recent call last):
  File "/SOLD2-main/misc/show.py", line 121, in <module>
    outputs = line_matcher([torch_img1, torch_img2])
  File "/SOLD2-main/misc/../model/line_matcher.py", line 253, in __call__
    self.line_detection(images[0], valid_masks[0],
  File "/SOLD2-main/misc/../model/line_matcher.py", line 97, in line_detection
    line_map, junctions, heatmap = self.line_detector.detect(
  File "/SOLD2-main/misc/../model/line_detection.py", line 122, in detect
    candidate_map = self.candidate_suppression(junctions,
  File "/SOLD2-main/misc/../model/line_detection.py", line 291, in candidate_suppression
    proj = (torch.einsum('bij,bjk->bik', cand_vecs, dir_vecs[..., None])
  File "//anaconda3/envs/newfuck/lib/python3.8/site-packages/torch/functional.py", line 344, in einsum
    return _VF.einsum(equation, operands)  # type: ignore
RuntimeError: shape '[1, 1, 2]' is invalid for input of size 0`

can you help me? thx a lot !

**Comment by rpautrat** [comment]
Hi, it seems that you are not using the latest version of the code (or at least your line numbers do not match the ones in the repo). The latest version fixed a few issues when the number of detected junctions is too small, which is what is happening in your case. So I would recommend upgrading to the latest version and trying again. Let me know if this does not solve the issue.

**Comment by xy-git** [comment]
thank you for your answer!
I try what you said, and now there is no errors.
but i don't understand, why this model can't detect any lines, which I just use sold2_wireframe.tar fine-turning in step5 for some epochs. can you help me? thanks

**Comment by rpautrat** [comment]
On which dataset did you fine-tune it? Did you try to visualize the pseudo ground truth to check that it was correct? You can use the notebook https://github.com/cvg/SOLD2/blob/main/notebooks/visualize_exported_dataset.ipynb to do so.
