### ISSUE TITLE
Unexpected key(s) in state_dict

### ISSUE THREAD

**Issue by xy-git** [cvg/SOLD2#36]
Hi !
when I run evaluate_line_repeatability.py and find error
`  File "/home/SOLD2-main/sold2_dev_code/evaluation/../model/line_detector.py", line 161, in __init__
    self.model.load_state_dict(checkpoint["model_state_dict"])
  File "/home/anaconda3/envs/newfuck/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SimpleNet:
	Unexpected key(s) in state_dict: "w_desc", "descriptor_decoder.convPa.weight", "descriptor_decoder.convPa.bias", "descriptor_decoder.convPb.weight", "descriptor_decoder.convPb.bias". `

I use the ckpt that you provide -- sold2_wireframe.tar
can u help me? thank you a lot !

**Comment by rpautrat** [comment]
Hi, these kinds of things happen because it is an uncleaned code... I think the problem there is just that sold2_wireframe.tar is the checkpoint for the detector+descriptor, whereas this code expect only the detector. You can use `strict=False` in load_state_dict to avoid this error message.

**Comment by xy-git** [comment]
thx, it works!
but when I use sold2_wireframe.tar to run the evaluate_line_repeatability.py
find bug in iter 760
`Iter:  760
	 Rep-05: 0.365194 	 Loc-05: 1.965726
	 Rep-10: 0.399680 	 Loc-10: 2.482098
	 Rep-15: 0.438374 	 Loc-15: 3.321471
	 Rep-20: 0.470594 	 Loc-20: 4.257963
	 Rep-25: 0.511610 	 Loc-25: 5.798089
	 Rep-35: 0.585993 	 Loc-35: 9.068738
	 Rep-45: 0.646584 	 Loc-45: 12.037303
	 Rep-55: 0.690976 	 Loc-55: 14.989575
	 average runtime: 0.104492 s/image
	 average number of segments: 32.483574 segs/image
Traceback (most recent call last):
  File "/home/xy/SOLD2-main/sold2_dev_code/evaluation/evaluate_line_repeatability.py", line 190, in <module>
    rep_results, loc_results, time_results, num_segments = evaluate_repeatability_v2(
  File "/home/xy/SOLD2-main/sold2_dev_code/evaluation/../evaluation/line_detect_eval.py", line 703, in evaluate_repeatability_v2
    outputs_target = line_detector(target_image, valid_mask, profile=True, return_heatmap=True)
  File "/home/xy/SOLD2-main/sold2_dev_code/evaluation/../model/line_detector.py", line 216, in __call__
    line_map, junctions, heatmap = self.line_detector.detect_torch(
  File "/home/xy/SOLD2-main/sold2_dev_code/evaluation/../model/line_detection.py", line 1401, in detect_torch
    junctions, line_map_pred = self.refine_junction_perturb(
  File "/home/xy/SOLD2-main/sold2_dev_code/evaluation/../model/line_detection.py", line 1689, in refine_junction_perturb
    refined_segments = torch.cat(refined_segment_lst, dim=0)
RuntimeError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors.  Available functions are [CPU, CUDA, QuantizedCPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].

CPU: registered at /pytorch/build/aten/src/ATen/CPUType.cpp:2127 [kernel]
CUDA: registered at /pytorch/build/aten/src/ATen/CUDAType.cpp:2983 [kernel]
QuantizedCPU: registered at /pytorch/build/aten/src/ATen/QuantizedCPUType.cpp:297 [kernel]
BackendSelect: fallthrough registered at /pytorch/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Named: registered at /pytorch/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
AutogradOther: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
AutogradCPU: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
AutogradCUDA: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
AutogradXLA: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
AutogradPrivateUse1: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
AutogradPrivateUse2: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
AutogradPrivateUse3: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:8078 [autograd kernel]
Tracer: registered at /pytorch/torch/csrc/autograd/generated/TraceType_2.cpp:9654 [kernel]
Autocast: registered at /pytorch/aten/src/ATen/autocast_mode.cpp:258 [kernel]
Batched: registered at /pytorch/aten/src/ATen/BatchingRegistrations.cpp:511 [backend fallback]
VmapMode: fallthrough registered at /pytorch/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
`
use sold2_synthetic.tar is ok.
and the rep and roc is not match in paper
If I do something wrong? can u help me? thank you !

**Comment by rpautrat** [comment]
Hi, since it is an uncleaned and unofficial code, I am not giving any support for it for now. I first need to clean it and publish an official version, but unfortunately I have many things in my todo list for now...

Regarding the different repeatability and ROC curves, it is probably because the detector evaluation of the paper was performed with another model with the detector only. The released model is slightly different as it combines the detector with the descriptor.
