### ISSUE TITLE
KeyError in step 4 when training on Holicity dataset

### ISSUE THREAD

**Issue by ISil14** [cvg/SOLD2#38]
Hello there, 

I am trying to train on the Holicity dataset, but when I run step 4 I get the following error: 

holicity_dataset.py", line 767, in __getitem__
    data["junctions"] = exported_label["junctions"]
KeyError: 'junctions'

When I print the keys of exported_label I get the following keys: 
['heatmap_cout', 'heatmap_prob_max', 'heatmap_prob_mean', 'image', 'junc_count', 'junc_prob_max', 'junc_prob_mean']

Do you know what might be the problem?
Thank you!

**Comment by rpautrat** [comment]
Hi, did you run step 3 without encountering any error?

**Comment by ISil14** [comment]
Yes, it didn't have any error.

**Comment by rpautrat** [comment]
The keys that you get are the ones generated by step 2. The requested 'junctions' key should be the output of step 3. So I think that something is wrong in the path that you are using for the ground truth.

Can you double-check that the path that you put in the config file `holicity.yaml` for the ground truth ('gt_source_train') is the same as the output name that you chose in step 3?

**Comment by ISil14** [comment]
Hi, indeed there was a mistake in the path. But now, I still end up having an error during training. 

train.py, line 257, in train_single_epoch
    junc_map = data["junction_map"].cuda()
KeyError: 'junction_map'

**Comment by rpautrat** [comment]
What is your config exactly?

Can you check that the code is going through this 'if' when you run it:
https://github.com/cvg/SOLD2/blob/492a71d6b9a9d8d14b6d6586627197d5f9a927f0/dataset/holicity_dataset.py#L773

**Comment by ISil14** [comment]
Yes, it does. But I realized that the error during the training happens only for a few images. If I skip those, the training goes through but then I run into another error during the validation. 

metrics.py", line 212, in average
    results[met] = self.metric_results[met] / self.count
Could this one also be caused by some faulty images?

**Comment by rpautrat** [comment]
I see, it is weird that the error only happens for a few images... Maybe there is a silent error during the ground truth generation and it is not properly generated for a few images.

What is the exact error that you get in the second case?

**Comment by ISil14** [comment]
Sorry, I didn't copy the last part of the error: 

metrics.py", line 211, in average
    results[met] = self.metric_results[met] / self.count
ZeroDivisionError: float division by zero

**Comment by rpautrat** [comment]
Hi, this self.count which is zero in your case is supposed to be the batch size. Or more precisely, the first dimension of the junction map returned by the dataloader. If you get a value of zero here, it means that somehow either your batch size is zero, or the junction map is not properly loaded.

**Comment by rpautrat** [comment]
I am closing this for now, feel free to reopen it if necessary.
