### ISSUE TITLE
A question about export line features

### ISSUE THREAD

**Issue by monarchdemon** [cvg/SOLD2#44]
Sorry, I am a rookie and I am very interested in your project.I have a question that how  can I  use the model to export line features (segments and descriptor maps) as follows:
ppython -m sold2.export_line_features --img_list <list to a txt file containing the path to all the images> --output_folder <path to the output folder> --checkpoint_path <path to your best checkpoint,>
what is the "-img_list <list to a txt file containing the path to all the images> -"  and "--checkpoint_path <path to your best checkpoint,>"? And how can get "-checkpoint_path <path to your best checkpoint,>".
Looking forward to your reply,thank you very much!

**Comment by rpautrat** [comment]
Hi, first download the [pre-trained model](https://www.polybox.ethz.ch/index.php/s/blOrW89gqSLoHOk/download) as explained in the ReadMe. Then replace <path to your best checkpoint,> with the path that leads to this pre-trained model.

**Comment by rpautrat** [comment]
I am closing it now, feel free to reopen it if you have more issues.
