### ISSUE TITLE
How to  make the figure like paper

### ISSUE THREAD

**Issue by monarchdemon** [cvg/SOLD2#45]
Sorry, I am a rookie and I am very interested in your project.I have a question that how can I make the figure like paper?
looking for your reply,thank you very much!

**Comment by rpautrat** [comment]
Which figure are you talking about?

**Comment by monarchdemon** [comment]
figure 4，figure 5 and figure 12

**Comment by rpautrat** [comment]
The code for these experiments has not been released. It has not been cleaned and I didn't think that it could have benefited very much the community, so I am not planning to release it.

**Comment by monarchdemon** [comment]
OK，thank you very much,but may I get the code for the experiments of figure 4，figure 5 and figure 12 for you by the eamil (benhe_cai@163.com) from you? To be sure, if this requeiset compromises your research, I apologize and will not make such a request again.

**Comment by rpautrat** [comment]
The uncleaned development code can be found here: https://github.com/cvg/SOLD2/issues/30#issuecomment-985026158

I don't have time to detail exactly how to re-run each experiment, but you can find the ROC in `evaluation/descriptor_evaluation.py`, the occlusion experiment in `evaluation/occluded_descriptor_evaluation.py`, and for the comparison with SuperPoint, you can visualize the correct/incorrect matches with the function 'plot_color_lines' of `misc/visualize_util.py`. You would need to use the official release of SuperPoint to get the SuperPoint matches (https://github.com/magicleap/SuperPointPretrainedNetwork).

**Comment by monarchdemon** [comment]
OK，thank you very much！
