### ISSUE TITLE
how can i get output images?

### ISSUE THREAD

**Issue by PilotPhil** [cvg/SOLD2#48]
Hi there

after i write a shell script like

python -m sold2.export_line_features \
--img_list /home/dwb/Documents/cloned/SOLD2/test/imgs.txt \
--output_folder /home/dwb/Documents/cloned/SOLD2/test/output \
--config /home/dwb/Documents/cloned/SOLD2/sold2/config/export_line_features.yaml \
--checkpoint_path /home/dwb/Documents/cloned/SOLD2/test/sold2_wireframe.tar

and excute it,it works fine,but i only get two files like
terrace1.sold2.npz 
or something extension with .sold2.npz. in the output folder.

so my question is how can i visualize the result image？

thanks!

**Comment by rpautrat** [comment]
Hi,

The script `export_line_features.py` generates indeed these .npz files, which you can then open with Numpy and they contain the detected line segments and descriptors. You can read them with the following code:
```
import numpy as np
file = 'terrace1.sold2.npz'
with open(file, 'r') as f:
    data = np.load(f)
    lines = data['line_seg']
    descriptors = data['descriptors']
```
But the easiest would be to use the provided notebook https://github.com/cvg/SOLD2/blob/main/notebooks/match_lines.ipynb, which shows how to directly detect and match lines. You can also see how to plot lines there.

**Comment by PilotPhil** [comment]
thanks very much
