### ISSUE TITLE
potential bug for other size images (not 512 by 512)

### ISSUE THREAD

**Issue by d5423197** [cvg/SOLD2#52]
Hello there,

Bug description: if the image size is not 512 by 512, the junctions and line_map we got from step 3 are based on the image which has been resized to 512 by 512. Now if we want to visualize the preds. We will go to train_preprocessing_exported (ex: in holicity_dataset), the image in data (one of the inputs) will be the original size of the image (ex: 2040 by 2040). The size is not equal to the size in the config file (512 by 512), so the code will resize the image, and the JUNCTIONS (the junction here is obtained based on 512 by 512 image).

In my opinion, you should not resize the junction here.

I don't know if there is any potential effect on line_map because I think the coordinate for line_map is based on the junctions.

Let me know if this is incorrect.

Thanks

**Comment by feiyu12138** [comment]
Hey,
I think ur right. When I try to construct my datasets with non 512*512 image. The junction label is just unmatched,giving rise to a long while wrong training process.

**Comment by feiyu12138** [comment]
when training with your own datasets, please make sure following codes commented:
junctions = (junctions * np.array(
                        self.config['preprocessing']['resize'], np.float)
                                    / np.array(size_old, np.float))

**Comment by rpautrat** [comment]
Hi, I think that you are indeed correct. This bug had never been caught because the Wireframe and Holicity images were already at 512x512, but it would not work for other image sizes.

I have fixed it now and pushed the new version. Thanks for reporting the bug!
