### ISSUE TITLE
Find the descriptor vector for any point

### ISSUE THREAD

**Issue by mahendrathapa** [cvg/SOLD2#54]
We can find the matched lines between 2 different images following this notebook: https://github.com/cvg/SOLD2/blob/main/notebooks/match_lines.ipynb

But how can we find the corresponding descriptor vector?

**Comment by mahendrathapa** [comment]
I am doing the following: 

```
outputs = line_matcher([torch_img1, torch_img2])
line_seg1 = outputs["line_segments"][0]
line_seg2 = outputs["line_segments"][1]
line_desc1 = line_matcher.line_detection(torch_img1)["descriptor"]
line_desc2 = line_matcher.line_detection(torch_img2)["descriptor"]

print("Input image shape", torch_img1.shape, torch_img2.shape)
print("Line seq shape", line_seg1.shape, line_seg2.shape)
print("Descriptor shape", line_desc1.shape, line_desc2.shape)

```

I am getting the response
```
Input image shape torch.Size([1, 1, 1133, 827]) torch.Size([1, 1, 1753, 1275])
Line seq shape (387, 2, 2) (300, 2, 2)
Descriptor shape torch.Size([1, 128, 283, 207]) torch.Size([1, 128, 438, 319])
```

Question:
1. How can I find the endpoint descriptor for the 387 line segment detected for the 1st image?

**Comment by rpautrat** [comment]
Sorry for the lack of details, here are more explanations on how to use the descriptor vectors.

The output of your line_desc1 and line_desc2 are dense descriptor maps that have the resolution of the original image x 0.25. So you need to extract the descriptor in these two maps at the location of the endpoints of your line segments. You can use the torch grid_sample function for that.

You could actually mimic this piece of code: https://github.com/cvg/SOLD2/blob/3fe359bfbb0e8d133451e2d32b4c0afb212cbaec/sold2/model/line_matching.py#L60-L63

In your case, line_points1 would be the list of endpoints in the image 1, i.e. `line_seg1.reshape(-1, 2)` (and similarly for line_points2). So to get the descriptors of line segments of image 1, you can do the following:
```
from sold2.misc.geometry_utils import keypoints_to_grid

grid1 = keypoints_to_grid(line_seg1.reshape(-1, 2), img_size1)
desc1 = F.normalize(F.grid_sample(line_desc1, grid1)[0, :, :, 0], dim=0).reshape(128, -1, 2).permute(1, 2, 0)
```
After this, `desc1` will be a [num_lines, 2, 128] tensor containing the descriptors of the endpoints of the lines in image 1.

**Comment by mahendrathapa** [comment]
Yeah, it works. Thank you :)
