### ISSUE TITLE
Question about occlusion

### ISSUE THREAD

**Issue by Zhuyawen7** [cvg/SOLD2#55]
Hi, thanks for your contribution
Is the indicator the occlusion of each line, or the percentage of occlusion of the entire image  in fig 5?
If it is the whole image, assuming 0.6 occlusion, your accuracy is about 0.7. Accuracy is the ratio of matching correct lines to detected lines or the ratio of matching correct lines to the all ground-truth line? Because I think if 0.6 is occluded for the whole image, then there will be no more matches than 0.4.

**Comment by rpautrat** [comment]
Hi, the percentage for the occlusion is the maximum percentage of occlusion for all lines in an image. In other words, for a percentage of s%, all lines inside the image are occluded between 0 and s%.

As stated in the paper, the reported accuracy is the ratio of correct matched lines over all ground truth line matches. Even if a line is occluded at 80%, it is still contributing to the accuracy computation, so it is possible to get an accuracy above 0.6 for an occlusion percentage of 0.4.

**Comment by Zhuyawen7** [comment]
> Hi, the percentage for the occlusion is the maximum percentage of occlusion for all lines in an image. In other words, for a percentage of s%, all lines inside the image are occluded between 0 and s%.
> 
> As stated in the paper, the reported accuracy is the ratio of correct matched lines over all ground truth line matches. Even if a line is occluded at 80%, it is still contributing to the accuracy computation, so it is possible to get an accuracy above 0.6 for an occlusion percentage of 0.4.

Thank for your reply.
May I ask which dataset is the official downloaded dataset used for the ETH3D dataset? distorted raw image or undistorted image？ 
![image](https://user-images.githubusercontent.com/100696862/163718325-c803dc7d-389a-4622-87a8-1c687b421a35.png)
![image](https://user-images.githubusercontent.com/100696862/163718439-5940593f-89a9-4d6b-b28f-5da84908203b.png)

**Comment by rpautrat** [comment]
We used the undistorted high-res images of the multi-view images of ETH3D. Undistorted images are needed to keep straight lines.

**Comment by Zhuyawen7** [comment]
> We used the undistorted high-res images of the multi-view images of ETH3D. Undistorted images are needed to keep straight lines.

Thank you!
Are you evaluating using only the training set or both training and test sets in eth3d?
I tried your eval on eth3d use your code, but I found that the number of pictures is 1453, The training set I get is only 444;
![image](https://user-images.githubusercontent.com/100696862/163718881-f6dc14e6-2e61-4cdf-acfd-b44b9b4540bd.png)

**Comment by rpautrat** [comment]
We used the training set only. The number 1453 refers to all pairs of images sharing at least 500 3D points, it is not the number of images.

**Comment by Zhuyawen7** [comment]
> We used the training set only. The number 1453 refers to all pairs of images sharing at least 500 3D points, it is not the number of images.

Thank you, Is it necessary to run export_baselines.py or export_descriptor.py first to evaluate the eth3d dataset? I haven't run it successfully
![image](https://user-images.githubusercontent.com/100696862/163719428-83234fd2-2274-446c-8552-6b0e728f7e62.png)

**Comment by rpautrat** [comment]
export_baseline.py is used to run the baselines such as LBD, WLD, etc. So it is up to you if you want to re-run this experiment as well or not. Otherwise, you only need to run export_descriptor.py.

**Comment by Zhuyawen7** [comment]
> export_baseline.py is used to run the baselines such as LBD, WLD, etc. So it is up to you if you want to re-run this experiment as well or not. Otherwise, you only need to run export_descriptor.py.

Thank you.
When i use export_descriptor.py, which --config will i need ?  I did not find eth3d_export_config.yaml in "/config"

**Comment by rpautrat** [comment]
You can use the config lcnn_export_config.yaml. Though I am not sure if the default parameters were the same to reproduce the experiment of the paper. Some parameters such as 'detect_thresh' might need to be tuned.

**Comment by Zhuyawen7** [comment]
ValueError: Caught ValueError in DataLoader worker process 0.0riginal Traceback (most recent call last) :
File " /home/anaconda3/envs/sold/lib/python3.6/site-packages/torch/utils/datal_utils/worker .py" ， line 185, in _worker_loop
data = fetcher.fetch(index)
File " /home/anaconda3/envs/sold/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py" ， line 44,in fetch
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/home/anaconda3/envs/ sold/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py" , line 44,in <listcomp>
data =[self.dataset[idx] for idx in possibly_batched_index]File "../dataset/eth3d_dataset.py" , line 253,in __getitem_ref dist_shape[1] *self.downsize_factor)
valueError: cannot reshape array of size 2945696 into shape (4136,6200)

After run export_descriptor.py, I run the descriptor_eval_eth_3d.ipynb, Have you ever encountered this problem?

**Comment by rpautrat** [comment]
Since this is the unofficial evaluation code, I am not giving any support for it for now. But I suppose this may come from a mismatch between the image size at export and evaluation time. Or some similar mismatch of shape.

**Comment by 3600067524** [comment]
Hi, thanks for your contribution.
I have a question about how to make the npz file in wireframe dataset. If I want to make my own training dataset, how should I generate this npz format label file?
