### ISSUE TITLE
How to calculate the accuracy evaluation index？

### ISSUE THREAD

**Issue by 3600067524** [cvg/SOLD2#58]
Hi，Thank you for your contribution! i want to konw how to calculate the line descriptor metrics.? How to know the number of correct matching lines and ground truth line matches.?
![image](https://user-images.githubusercontent.com/103869484/166105566-1186ded9-c266-4521-ab67-f22a9a43f7e6.png)

**Comment by rpautrat** [comment]
Hi, the ground truth matches are obtained either by warping the lines from one image to another with the ground truth homography (e.g. for the Wireframe dataset), or with the ground truth depth and camera parameters (e.g. for ETH3D). When a reprojected line falls close enough to another line (with respect to a line distance metric and a given threshold), they are considered to be matched.

The evaluation scripts are not officially released, but you can find a dev and uncleaned version here: https://github.com/cvg/SOLD2/issues/30#issuecomment-985026158. I am not giving any support for it though, but you can see how the ground truth matches are obtained at least.

**Comment by 3600067524** [comment]
Hi!Thank you for your reply
Can you answer me that 
![image](https://user-images.githubusercontent.com/103869484/166135813-f4cd3d3c-262d-4b15-9706-48025f75af06.png)
print(len(matched_lines1)) and print(len(matched_lines2)) is this the total number of match lines output?
print(len(line_seg1)) Is it the total number of detection lines in img1 output?
how can i get the correct line matches from the match_lines.ipynb and the visualize_util.py?

**Comment by rpautrat** [comment]
Hi, yes you are correct. `print(len(matched_lines1))` gives the number of matches output by SOLD2, and `print(len(line_seg1))` the number of its lines detected in image 1.

You cannot obtain the ground truth matches from the notebook, because you do not have access to the depth and camera parameters necessary to unproject lines in 3D. You need to follow the instructions in previous message for that.

**Comment by 3600067524** [comment]
Hi!Thank you for your reply.I will try.
