### ISSUE TITLE
Homography estimation

### ISSUE THREAD

**Issue by feiyu12138** [cvg/SOLD2#59]
Hey,

Thank you for your exciting paper! 

However, I got a trivial problem when I read it, that is, how to estimate the Homograhy matrix in terms of line segment feature.
Due to the remarkable change of end point considering that occlusion, it will cause some problem considering the line segment as two endpoints. 

Though it's a fundamental problem, I couldn't find effective solution. 

Hope for reply!

**Comment by rpautrat** [comment]
Hi, when computing a homography matrix from a set of matched line segments, you should not consider the endpoints of the lines. You should instead consider the full lines, and use them in a solver to get the homography. You can find the derivation for example here: https://webdiis.unizar.es/~csagues/english/publicaciones/04LNAI-cp.pdf

**Comment by feiyu12138** [comment]
Thank you for answer! This derivation is clear and problem-solving.
