### ISSUE TITLE
Preprocessed ETH3D dataset

### ISSUE THREAD

**Issue by angshine** [cvg/SOLD2#6]
Hi, thanks for releasing this great work!

Would you like to release the preprocessed ETH3D dataset (the inpainted depth) for a consistent evaluation of future works?

**Comment by rpautrat** [comment]
Hi,

Sure, you can find the inpainted depth of the high-res multi-view training data of the ETH3D dataset [here](https://www.polybox.ethz.ch/index.php/s/ghOch9ii93LH1aq). Each image corresponds to the depth of the distorted image downsized by a factor of 8. Note that we did not fully inpaint the images, but we only added a few pixels around each existing depth value (10 pixels if I remember correctly), as it was sufficient to recover most lines without too much loss of accuracy of the depth.

The depth is stored as unsigned integer 16 and a value of 0 means an invalid depth value. You can read it in Python with OpenCV in the following way:
```
depth = cv2.imread(depth_img_path, cv2.IMREAD_ANYDEPTH)
depth = depth.astype(np.float32) / 256
```
