### ISSUE TITLE
some questions in visualize_exported_dataset.ipynb

### ISSUE THREAD

**Issue by 3600067524** [cvg/SOLD2#60]
I customized my own dataset, but the following errors occurred when running the file visualize_exported_dataset.ipynb. Can you help me solve it
![%38F%EX{}$6 F_{QED$ASHH](https://user-images.githubusercontent.com/103869484/168428124-d0851061-ac81-4873-92b0-53faa74275bc.png)

**Comment by rpautrat** [comment]
Hi, I think that this issue has been resolved in several previous issues. What is your 'return_type' in the config file you used? It should be set to 'paired_desc' to be able to load pairs of images and to get this missing 'ref_image'.

**Comment by 3600067524** [comment]
i set it，but it does‘t work
![image](https://user-images.githubusercontent.com/103869484/168429720-952365a1-8833-4e5c-b979-ad7e46873cd8.png)

**Comment by 3600067524** [comment]
![image](https://user-images.githubusercontent.com/103869484/168536722-7bff62f5-af8d-4ee0-9eba-eb096d22358f.png)
i debug it ,but the reason that i don't undestand

**Comment by rpautrat** [comment]
Hi, sorry for the late reply. If you have a custom dataset, then you need to generate a ground truth for it (step 2 and 3 of the Readme). Here you seem to be using wireframe_train_gt.h5 and wireframe_test_gt.h5, which are irrelevant for your custom dataset.

**Comment by rpautrat** [comment]
I am closing this for now, feel free to reopen if you need additional assistance.
