### ISSUE TITLE
the matching between day and night

### ISSUE THREAD

**Issue by zhengshunkai** [cvg/SOLD2#65]
Hi,Thx for your great work..
I found the matching between day and night is bad,can you give me some suggestion? Than you very much. I use the pre_trained model for test and also train by myself.
![图片](https://user-images.githubusercontent.com/9248030/182060827-55cb8d93-3c30-406f-9623-29696c193228.png)
![图片](https://user-images.githubusercontent.com/9248030/182060851-30c626cd-a50c-44d5-86bb-b7c11ebf485f.png)

**Comment by rpautrat** [comment]
Hi, the pre-trained model was not trained on day-night images and is thus not robust to it. If you want to make it more robust to these changes, I would suggest training on another dataset or adding strong photometric augmentation to mimic night-time images. For the day-night dataset, you could try the Aachen dataset like in the [R2D2 paper](https://europe.naverlabs.com/wp-content/uploads/2019/09/R2D2-Repeatable-and-Reliable-Detector-and-Descriptor-2.pdf), or the [VIDIT dataset](https://github.com/majedelhelou/VIDIT) for example.

**Comment by zhengshunkai** [comment]
> Hi, the pre-trained model was not trained on day-night images and is thus not robust to it. If you want to make it more robust to these changes, I would suggest training on another dataset or adding strong photometric augmentation to mimic night-time images. For the day-night dataset, you could try the Aachen dataset like in the [R2D2 paper](https://europe.naverlabs.com/wp-content/uploads/2019/09/R2D2-Repeatable-and-Reliable-Detector-and-Descriptor-2.pdf), or the [VIDIT dataset](https://github.com/majedelhelou/VIDIT) for example.

Hi,thanks for your reply.
I have trained new model in the dark dataset. Between two frames(day vs day or night vs night),the matching looks reasonable,but the day-night matching looks unreasonable.According to my understanding, using unsupervised model does not train descriptor during the day and night,the result maybe not very good because of this.

**Comment by rpautrat** [comment]
I am not sure to understand correctly. Did you have day-night pairs in your training set or only day-day and night-night pairs? Because you would need to train with day-night as well.
If you did, then I am afraid that there is not so much that you can do. Matching across large illumination variation is still an ongoing direction of research nowadays.

**Comment by zhengshunkai** [comment]
Sorry, I didn't make it clear.
I trained the dataset include the day images and night images,but not including day-night pairs because I didn't  know the pre-matching relationship between them.
 When use the own trained model for test,Between two frames(night vs night),the matching looks reasonable,but the day-night matching looks unreasonable.

**Comment by zhengshunkai** [comment]
Sorry, I didn't make it clear.
I trained the dataset include the day images and night images,but not including day-night pairs because I didn't  know the pre-matching relationship between them.
 When use the own trained model for test,Between two frames(night vs night),the matching looks reasonable,but the day-night matching looks unreasonable.

**Comment by rpautrat** [comment]
I see, then there is hope to improve your day-night matching performance. You need to have day-night pairs in the training set as well, for example using VIDIT, where it is easy to get the ground truth matching.

**Comment by zhengshunkai** [comment]
> 
Hello,what is the VIDIT?

**Comment by rpautrat** [comment]
> Hi, the pre-trained model was not trained on day-night images and is thus not robust to it. If you want to make it more robust to these changes, I would suggest training on another dataset or adding strong photometric augmentation to mimic night-time images. For the day-night dataset, you could try the Aachen dataset like in the [R2D2 paper](https://europe.naverlabs.com/wp-content/uploads/2019/09/R2D2-Repeatable-and-Reliable-Detector-and-Descriptor-2.pdf), or the [VIDIT dataset](https://github.com/majedelhelou/VIDIT) for example.

**Comment by rpautrat** [comment]
I am closing this for now, feel free to reopen if you need additional assistance.
