### ISSUE TITLE
Question in superpoint backbone

### ISSUE THREAD

**Issue by cathy-ji** [cvg/SOLD2#66]
Hi, thanks for sharing your work.
I've download the pre-trained model (sold2_synthetic.tar) and test it on images,it works great(figure 1).But, when I changed the backbone to the superpoint and trained the model on the synthetic datasets, something went wrong(figure 2). Have you ever met the same problems when adjust parameters? I wonder how to find the problems. 
<img width="495" alt="image" src="https://user-images.githubusercontent.com/51524778/185584169-37914e9e-95b0-4c1c-9839-393f5505171b.png">

Here is the code I changed.
(1)sold2/config/synthetic_datasets 
generation:
    split_sizes: {'train': 5000, 'val': 1000, 'test': 400}  #your code is {'train': 20000, 'val': 2000, 'test': 400}

(2)sold2/config/train_detector.yaml
backbone: "superpoint"#your code is lcnn
train:
  batch_size: 16 #your code is 6
  num_workers: 8 #your code is 8
test:
  batch_size: 16 #your code is 6
  num_workers: 8 #your code is 8
(3)sold2/train.py
model = torch.nn.DataParallel(model)#Enables the model to parallel training

**Comment by rpautrat** [comment]
Hi, as far as I remember, the superpoint backbone was working fine, its performance was just lower than the LCNN backbone. Did you also try re-training with the lcnn backbone, just to make sure that this one was working correctly for you?

**Comment by cathy-ji** [comment]
Thank you for your suggestions, I'd like to try it later.
