### ISSUE TITLE
combining both points and lines into a unified framework

### ISSUE THREAD

**Issue by 2017DEVIL** [cvg/SOLD2#67]
Hi, thanks for sharing your work.
In the paper, you mentioned combining both points and lines into a unified framework.Is this work you are doing? What do you think are the difficulties of this work

**Comment by rpautrat** [comment]
Yes, I am currently investigating this unified approach, together with someone else. We will probably release the final version on Github soon and I can let you know about it.

The challenges are mainly to keep a compact network, while maintaining the performance of the points or lines only approaches.

**Comment by 2017DEVIL** [comment]
Are there any relevant papers available for reference?

**Comment by rpautrat** [comment]
Not that I know of...

**Comment by 2017DEVIL** [comment]
> Yes, I am currently investigating this unified approach, together with someone else. We will probably release the final version on Github soon and I can let you know about it.
> 
> The challenges are mainly to keep a compact network, while maintaining the performance of the points or lines only approaches.

I am also interested in this matter and I think it makes a lot of sense. May I ask if you are working on the SOLD2 code? Will there be a corresponding paper published for the upcoming code release?

**Comment by rpautrat** [comment]
For now it is a student project that I am supervising, and there is no targeted publication. I don't see enough novelty to publish it for now, so it might just end up as a released code on Github. Part of it is re-using ideas of SOLD2 and other previous baselines as well.

**Comment by rpautrat** [comment]
Hi @2017DEVIL , I forget to notify you, but the joint point and line framework has been released here: https://github.com/hkkkpang/Joint-PL-network

I hope this kind be useful to you!
