### ISSUE TITLE
Query regarding testing of SOLD on personal dataset

### ISSUE THREAD

**Issue by maazmb** [cvg/SOLD2#7]
Dear Admin,
Firstly thanks for sharing your code project. I tested the model on some images from wireframe dataset and the results were fine. However, when i ran the model on my personal dataset, it shows inadequate performance incases of slight viewpoint, rotation changes. It gives wrong matches mostly where matches are  also being showed for portion of non-overlapping scenes in the two images even. I couldn't comprehend as to what could be the possible reasons for these mismatches as from the paper the matching method based on Needleman Wunsch seems very comprehensive to remove such outlier matches. Perhaps the D2Net descriptors arent distinctive enough or i should try training the model on my dataset. Your opinions are highly appreciated. Great work and Many Thanks..:)

**Comment by maazmb** [comment]
Hi, the dataset contain views such as inside of shopping mall. I was just confused as to why it shows wrong matches at portion of images where it should have just shown no matches at all. I get your point of fine tuning. Thanks Remi..:)

**Comment by rpautrat** [comment]
At matching time, the network doesn't know what portion of the image is shared between the two views, so it tries to match everything. To get rid of these matches, you would need to run some geometric verification afterwards to keep only the inlier matches. Adding a ratio test criteria could also help to get rid of these spurious matches. We haven't tried it though.

**Comment by maazmb** [comment]
Thanks for the immediate and thorough replies. Wish you best for your future endeavors.
