### ISSUE TITLE
question about the steps4 on holicity_dataset

### ISSUE THREAD

**Issue by DennisJcy** [cvg/SOLD2#70]
Hi,i follow your guide and face a mistake in steps 4,and im sure that i run the step2 and 3 to generate the gt data according your advise in [#19](https://github.com/cvg/SOLD2/issues/19) .
Can you give me some advice?thank you very much!

[Info] Training mode
         Output path: ./experiments/sold2_hair
         Initializing dataset...
[Info] Initializing Holicity dataset...
         Found filename cache holicity_train_cache.pkl at ./datasets/Holicity
         Load filename cache...
[Info] Successfully initialized dataset
         Name: Holicity
         Mode: train
         Gt: None
         Counts: 12

[Info] Initializing Holicity dataset...
         Found filename cache holicity_test_cache.pkl at ./datasets/Holicity
         Load filename cache...
[Info] Successfully initialized dataset
         Name: Holicity
         Mode: test
         Gt: None
         Counts: 3

         Successfully intialized dataloaders.

        --------Initializing model----------
         [Debug] Adding w_junc with value 0.000000 to model
         [Debug] Adding w_heatmap with value 0.000000 to model
        Model architecture: simple
        Backbone: lcnn
        Junction decoder: superpoint_decoder
        Heatmap decoder: pixel_shuffle
        -------------------------------------
         Successfully initialized model

================== Training ====================
Traceback (most recent call last):
  File "sold2/experiment.py", line 229, in <module>
    main(args, dataset_cfg, model_cfg,export_dataset_mode=args.export_dataset_mode, device=device)
  File "sold2/experiment.py", line 112, in main
    train(args, dataset_cfg, model_cfg, output_path)
  File "sold2/experiment.py", line 82, in train
    train_net(args, dataset_cfg, model_cfg, output_path)
  File "/home/pc/SOLD2/sold2/train.py", line 179, in train_net
    epoch=epoch)
  File "/home/pc/SOLD2/sold2/train.py", line 253, in train_single_epoch
    junc_map = data["junction_map"].cuda()
KeyError: 'junction_map'

**Comment by rpautrat** [comment]
Glad that you solved it. I am closing this now.
