### ISSUE TITLE
What computing power is needed to achieve good results

### ISSUE THREAD

**Issue by sysu17363087** [cvg/SOLD2#72]
The detection rate you showed in the video is very fast. I would like to know what computing power is needed to achieve good results. I have tested the code on the Nvidia Jetson AGX Xavier. It takes about 1s to estimate a picture.

**Comment by rpautrat** [comment]
Hi, the video is only for presentation purposes, so it was generated by running SOLD2 offline, frame-by-frame, and then putting all frames together in a video.

This code has not been optimized for real-time inference, but there is a large room for improvement. Some operations are still done on CPU, while they could be moved to GPU for faster inference for example. On a high-end GPU (e.g. RTX >1080), detecting and matching lines should take 100ms or less already.

**Comment by sysu17363087** [comment]
> 

Thank you for replying. I will look into this.
