### ISSUE TITLE
How to match lines detected by LSD

### ISSUE THREAD

**Issue by JosepLee** [cvg/SOLD2#73]
Hello, thank you very much for your work!
I wonder how to match lines detected by LSD with our descriptor.
I can only use the code in the jupyter notebook to match lines detected by SOLD2.

**Comment by rpautrat** [comment]
Hi,

The current repo doesn't allow you to match LSD lines directly, but it is fairly easy to adapt it to do so. Once you have detected your LSD lines (I recommend using [this repo](https://github.com/iago-suarez/pytlsd), which produces much better results than the OpenCV version), you can run the forward pass of SOLD2 and extract the dense descriptors. Then you can use our line matcher with SOLD2 descriptors and LSD lines [here](https://github.com/cvg/SOLD2/blob/9d8bc70251df95954c65da787cdc5ff34fdc8d5b/sold2/model/line_matching.py#L28).

**Comment by LikeRain0** [comment]
@JosepLee  hello
Have you implemented matching using the lines detected by LSD?
I'm very interested. If you implement it, can you tell me how to do it?
I would appreciate it very much if you could reply！！！

**Comment by rpautrat** [comment]
Hi, you could proceed as follows to match LSD lines with SOLD2:

1. Install the pytlsd python package.
2. Try [this gist](https://gist.github.com/rpautrat/78185bb1ed4c042eb0ebe27bd7295bdd), which is basically replacing the SOLD2 lines with LSD.

**Comment by LikeRain0** [comment]
@rpautrat 
Thank you very much. 
I have solved this problem. I use LSD to extract line segments from one image, and then use SOLD2 to extract line segments from another image, and then use SOLD2 to describe and match line segments from these two images.
