### ISSUE TITLE
Which GPU did the paper use when inferencing?

### ISSUE THREAD

**Issue by lnexenl** [cvg/SOLD2#77]
HI, I am doing some profiling work on Wireframe recently. However, I found when running export_line_features.py, Nvidia driver allocates GPU memory for every single image. And this slows down inference speed a lot (~8 fps)

But if I resize image to a certain size (e.g. 500x500) before sending it to the network, Nvidia driver only allocates memory once, and inference speed is about 60fps when images are resized, which is much faster than original script.

This is really weird, so I am curious on which GPU did you test your network? It took less than 100 ms for one image as shown in your paper.

(P.S. I am running scripts on RTX 3090)

**Comment by rpautrat** [comment]
Hi, I am not sure to understand what you did exactly. What was the size of the image when you got 8 fps?

We used an RTX 2080 Ti to get the timings in the paper, and averaged it over many images. So you should have a faster inference with your GPU in theory.
