### ISSUE TITLE
Run error when matching lines between two images

### ISSUE THREAD

**Issue by weiningwei** [cvg/SOLD2#8]
Hello! Firstly thanks for  your code. I can run the file [notebooks/match_lines.ipynb](url) normally in most cases. But when I match this two images as follws, the code run error. 
![000033](https://user-images.githubusercontent.com/38557780/119144130-f2f74580-ba7a-11eb-9f8f-c208b7ac8d6c.png)
![000034](https://user-images.githubusercontent.com/38557780/119144208-09050600-ba7b-11eb-81e2-f90d09c76efc.png)
And the output error are also  as follws:
![image](https://user-images.githubusercontent.com/38557780/119145240-07880d80-ba7c-11eb-947d-ebe95db84385.png)

**Comment by rpautrat** [comment]
Hi, thanks a lot for reporting the bug!

I just pushed a fix, it should work now. The bug was happening when very few lines were detected in the image.

**Comment by weiningwei** [comment]
Hi, I tried it and it works. Thank you a lot.

**Comment by weiningwei** [comment]
Hi, sorry to bother you again. But when I try to mathch the lines from another two images, I met another error again.
![image](https://user-images.githubusercontent.com/38557780/119216922-326c7300-bb09-11eb-99a5-408ffbe2152d.png)

**Comment by rpautrat** [comment]
Thanks again for reporting this, this is very useful for us to improve the code. I think this was happening because no line were detected at all. I pushed a fix, did it solve the bug?

**Comment by weiningwei** [comment]
It seems  it don't solve this bug. I upload the error image as follows.
![000179](https://user-images.githubusercontent.com/38557780/119221505-54262400-bb22-11eb-92a7-5f1aa42f2acf.png)

And when I run the file [export_line_features.py](url) to test the image whether have lines, it output the error as follows.
`
        --------Initializing model----------
         [Debug] Adding w_junc with value 0.000000 to model
         [Debug] Adding w_heatmap with value 0.000000 to model
         [Debug] Adding w_desc with value 0.000000 to model
        Model architecture: simple
        Backbone: lcnn
        Junction decoder: superpoint_decoder
        Heatmap decoder: pixel_shuffle
        -------------------------------------
[Debug] detect_thresh: 0.5
[Debug] num_samples: 64
[Debug] sampling_method: local_max
[Debug] inlier_thresh: 0.99
[Debug] use_candidate_suppression: True
[Debug] nms_dist_tolerance: 3.0
[Debug] use_heatmap_refinement: True
[Debug] heatmap_refine_cfg: {'mode': 'local', 'ratio': 0.2, 'valid_thresh': 0.001, 'num_blocks': 20, 'overlap_ratio': 0.5}
[Debug] use_junction_refinement: True
[Debug] junction_refine_cfg: {'num_perturbs': 9, 'perturb_interval': 0.25}
         Successfully initialized model
  0%|                                                                                                                                                            | 0/1 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "my_line_detect.py", line 98, in <module>
    args.output_folder, args.multiscale)
  File "my_line_detect.py", line 46, in export_descriptors
    ref_detection = line_matcher.line_detection(img)
  File "/home/wei/sold2/SOLD2/model/line_matcher.py", line 101, in line_detection
    junctions, heatmap, device=self.device)
  File "/home/wei/sold2/SOLD2/model/line_detection.py", line 214, in detect
    junctions, line_map_pred, heatmap, H, W, device)
  File "/home/wei/sold2/SOLD2/model/line_detection.py", line 389, in refine_junction_perturb
    refined_segments = torch.cat(refined_segment_lst, dim=0)
RuntimeError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors.  Available functions are [CUDATensorId, CPUTensorId, VariableTensorId]`
