### ISSUE TITLE
A question：about multiscale_line_detection and line_detection.

### ISSUE THREAD

**Issue by LikeRain0** [cvg/SOLD2#80]
Hello, I'm sorry to bother you again,I have a question. 

Currently, I am using line_detection in line_matcher.py. What is the difference between it and multiscale_line_detection?
Will it make line detection and matching better? 
Is it designed for image scale transformation or angle of view change? 
Will it take more time to run multiscale detection?

I look forward to hearing from you very much！

**Comment by rpautrat** [comment]
Hi, the multiscale_line_detection is a brute-force method to obtain higher invariance to scale changes. It basically runs the network on the same image, upsampled and downsampled at different resolutions (x1 and x2 by default), then aggregate the results in the original scale.

This will make the detection and matching more robust to scale changes, but may decrease the performance if the test set has few scale changes. So this is purely about scale, there is no improvement with respect to other viewpoint changes and the multiscale option is slower than the default one.

**Comment by LikeRain0** [comment]
OK,thank you very much！ I understand it！ 
Then if I want to improve the quality of matching or reduce the number of matches, which of the following parameters should I adjust?

```
'line_matcher_cfg': {
        'cross_check': True,
        'num_samples': 5,
        'min_dist_pts': 8,
        'top_k_candidates': 10,
        'grid_size': 4
    }
```

**Comment by rpautrat** [comment]
These are the optimal parameters in terms of performance and speed. You could try increasing the 'top_k_candidates' a bit for a slightly better performance, but it will also get much slower, so I would just keep all these parameters fixed.

**Comment by LikeRain0** [comment]
OK，I see. 
Thank you for your reply. 
I wish you a happy life！
