### ISSUE TITLE
Question about the sold2_wireframe.tar

### ISSUE THREAD

**Issue by djidan10** [cvg/SOLD2#9]
Hi, 

I would like to make sure about the sold2_wireframe.tar checkpoint if it is the full version of the paper trained with both synthetic and Wireframe?

Also, I couldn't find explicitly all the training information for the full version, like the number of images included in the synthetic training, the number of lines, could you please share with us these information plus the number of epochs for the synthetic and the wireframe?  

one more thing, for the data augmentation, did you use the same as in SuperPoint ?

Thanks

**Comment by rpautrat** [comment]
Hi,

Yes, the provided checkpoint `sold2_wireframe.tar` is the one of the paper, trained first on the synthetic dataset and then on Wireframe.

We used 20000 images per type of shapes (simple lines, polygons, checkerboards, etc) in the synthetic dataset. The number of lines per image thus depends on the type of shape and is random, so I cannot say.

The detector network was first trained on the synthetic dataset for about 40 epochs, then trained on Wireframe for about 200 epochs, and finally the whole pipeline with descriptors was fine-tuned on Wireframe for 20 epochs. But I recommend to monitor the metrics in tensorboard and to stop the training once they have converged.

For the data augmentation, we indeed used similar ones as in SuperPoint.

I hope this answers your questions.

**Comment by djidan10** [comment]
Yes, it answers perfectly my answer, thank you so much @rpautrat for the precious information

**Comment by djidan10** [comment]
Hi again,

a fast question, is there any length limitation for the line detection ? I tried to check the parameters but I get lost, 

Thanks in advance

**Comment by brade31919** [comment]
Hi @djidan10 ,

What do you mean by length limitation? In our method, given two junctions on the image (within image border), our method should be able to perform the detection. I think we didn't impose a limitation on it, but you can always implement your own rules (get rid of short segments for example) based on the detection results.

**Comment by djidan10** [comment]
Thanks a lot for your answer
